name: Daily Job Alert

on:
  schedule:
    - cron: '0 3 * * *'  # सुबह 8:30 बजे IST (03:00 UTC)
  workflow_dispatch: 

jobs:
  run-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Daily Alert API
        run: curl -X GET "https://us-central1-studymaterial-406ad.cloudfunctions.net/triggerDailyAlert"
